### ISSUE TITLE
Add Changelog for Korrel8r releases

### ISSUE THREAD

**Issue by vprashar2929** [korrel8r/korrel8r#102]
It would be really helpful to have a Changelog added for every Korrel8r release that highlights any new changes, bug fixes, etc.

**Comment by alanconway** [comment]
Agreed we should start a change log before the next preview release.

I think this has to be a manual part of the release process where a human translates the git commit history into user-readable release notes. I already tried generating a changelog automatically from the git log, but I removed it because it doesn't provide any value over the git log itself.

**Comment by vprashar2929** [comment]
There are some GH actions available that can automate the Changelog process. We can definitely explore those. For the time being I was thinking of the manual way through GH which takes a diff between two tags and generates changelog automatically. Wdyt?

<img width="1365" alt="Screenshot 2024-05-10 at 3 06 32 PM" src="https://github.com/korrel8r/korrel8r/assets/115542213/f696d978-48a8-498d-a907-69ae813e3e83">
